---
title: Modelo Entidad-Relacion — Modelo Generico Inicial (Entrega 1)
---
erDiagram
    EDICION_MUNDIAL ||--o{ ESTADIO   : "inscribe"
    EDICION_MUNDIAL ||--o{ SELECCION : "convoca"
    EDICION_MUNDIAL ||--o{ PARTIDO   : "programa"
    ESTADIO         ||--o{ PARTIDO   : "aloja"
    PARTIDO         ||--|{ PARTICIPACION_PARTIDO : "registra"
    SELECCION       ||--o{ PARTICIPACION_PARTIDO : "participa_en"

    EDICION_MUNDIAL {
        NUMBER   id_edicion   PK "Identificador de la edicion"
        NUMBER   anio         UK "Un unico mundial por anio"
        VARCHAR2 pais_sede       "Pais o paises anfitriones"
        VARCHAR2 lema            "Opcional"
        DATE     fecha_inicio    "Partido inaugural"
        DATE     fecha_fin       "Final. Debe ser posterior al inicio"
    }

    ESTADIO {
        NUMBER   id_estadio PK "Identificador del estadio"
        NUMBER   id_edicion FK "CASCADE. Parte de la clave candidata"
        VARCHAR2 nombre     UK "Unico dentro de la edicion"
        VARCHAR2 ciudad        "Ciudad sede"
        NUMBER   capacidad     "Aforo. Entre 20.000 y 150.000"
    }

    SELECCION {
        NUMBER   id_seleccion  PK "Identificador de la seleccion"
        NUMBER   id_edicion    FK "CASCADE"
        VARCHAR2 pais          UK "Unico dentro de la edicion"
        VARCHAR2 confederacion    "CONMEBOL UEFA CAF AFC CONCACAF OFC"
        VARCHAR2 grupo            "Letra A-L. NULL si no ha sido sorteada"
    }

    PARTIDO {
        NUMBER    id_partido            PK "Identificador del partido"
        NUMBER    id_edicion            FK "RESTRICT. Borrado determinista"
        NUMBER    id_estadio            FK "FK compuesta con id_edicion"
        TIMESTAMP fecha_hora            UK "Unica por estadio. Evita cruce de agenda"
        VARCHAR2  fase                     "Fase de Grupos hasta Final"
        NUMBER    asistencia_registrada    "NULL si no se ha jugado"
    }

    PARTICIPACION_PARTIDO {
        NUMBER   id_participacion PK "Identificador de la participacion"
        NUMBER   id_partido       FK "CASCADE. Dependencia de existencia"
        NUMBER   id_seleccion     FK "RESTRICT. No se borra con historial"
        VARCHAR2 condicion        UK "LOCAL o VISITANTE. Unica por partido"
        NUMBER   goles_marcados      "Entre 0 y 30"
    }
